In [ ]:
# Lab03 Numpy Basics

In [5]:
# NumPy Basics
import numpy as np

s = np.arange(12)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
# 1) Show all element of s
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
# 2) Show the third element of s
print(s[2])

# 2) Show the last element of s
print(s[-1])

2
11


In [10]:
# 3) Show the third to last element of s
print(s[-1])
# Show the third to seventh element of s
print(s[2:7])


11
[2 3 4 5 6]


In [14]:

# 4) Show the total of s
print(s.sum())

# Show the smallest value of s
print(s.min())

# Show the average value of s
print(s.mean())

# Show the largest value of s
print(s.max())

66
0
5.5
11


In [39]:
# 5) if array change values, will s change values too? why?
# show s values
arry = s
arry[1]= -1


[ 0 -1  2  3  4  5  6  7  8  9 10 11]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [17]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
print(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [18]:
matrix = np.array(data)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# 6)Show the element of first row of second col of matrix
print(matrix[0,1])

# 6)Show the element of second row of first col of matrix
print(matrix[1,0])

2
4


In [22]:
# 7 )Show all elements of first row in matrix
print(matrix[0,])

#  Show all elements of second row in matrix
print(matrix[1,])

# Show all elements of last row in matrix
print(matrix[2,])

[1 2 3]
[4 5 6]
[7 8 9]


In [46]:
# 8) Show all elements of first col in matrix
print(matrix[:,0])

# Show all elements of third col in matrix
print(matrix[:,1])

# Show all elements of last col in matrix
print(matrix[:,2])

[1 4 7]
[2 5 8]
[3 6 9]


In [43]:
print( matrix)
# Show second rows, and second col to last col's elements in matrix



[[ 1 -1  3]
 [ 4  5  6]
 [ 7  8  9]]
[5 6]


In [92]:
print(matrix)
# 5) Show the total of s
print(s.sum())
# Show the smallest value of s
print(s.min())
# Show the average value of s
print(s.mean())

# Show the largest value of s
print(s.max())

# The sum of second col
print(s[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
66
0
5.5
11


IndexError: too many indices for array